### PR TITLE
Improve Ddoc formatting and show function intellisense while typing parameters Fixes Pure-D/code-d#51

### LINKED ISSUE #51: Provide precompiled binaries for OS X
Currently only binaries for Linux and Windows are provided. Is it possible to also provide binaries for OS X?

### PR DESCRIPTION
**Pull request by jonathanballs**
So this pull request should really improve the utility and usability of the documentation viewer. The viewer has been fully stylised (including params formatted separate lines etc.) and will now stay open while you are typing the arguments for the function. The algorithm for detecting whether the cursor is in the middle of a function call is a bit basic but does the job fine. Let me know what you think :thinking: 

calltips

### CODE REVIEW

File: source/served/commands/calltips.d [hunk 1]
```diff
@@ -59,14 +69,28 @@ SignatureHelp provideDSignatureHelp(TextDocumentPositionParams params,
...
+	// work for 90%+ of cases.
+	import std.algorithm : countUntil;
+	import std.range: retro;
+	auto openBracketOffset = document.text[0..currOffset].retro().countUntil("(");
+	auto closeBracketOffset = document.text[0..currOffset].retro().countUntil(")");
+	auto nlBracketOffset = document.text[0..currOffset].retro().countUntil("\n");
+	if (openBracketOffset >= 0 && openBracketOffset < closeBracketOffset
+			&& openBracketOffset < nlBracketOffset) {
+		currOffset -= openBracketOffset;
+	}
```
Comment (WebFreak001) [inline source/served/commands/calltips.d]: I don't like that this is dependent on there being a new line and also only working in one single line and only working if the opening parenthesis is after any closing parenthesis.

This means these wouldn't work:
```d
myFunction(
   4, );

myFunction(someCall(), );
```

But because the `activeParameter` value would best use the AST, we can just pass this with the AST then

File: source/served/commands/complete.d [hunk 2]
```diff
@@ -138,6 +138,13 @@ string substr(T)(string s, T start, T end)
 	return s[start .. end];
 }
 
+/**
+ * Take a function signature and return an array of parameters. May wish to do
+ * this in dparse or a library created for this purpose but seems to work fine.
+ * Params:
+ * 		sig = a string of a function signature e.g. `int f(string arg);`
+ *		exact = perform a more more accurate but slower parsing (I think).
```
Comment (WebFreak001) [inline source/served/commands/complete.d]: Sorry forgot to push this comment yet. Here is the docs I put in:
```d
/// Extracts all function parameters for a given declaration string.
/// Params:
///   sig = the function signature such as `string[] example(string sig, bool exact = false)`
///   exact = set to true to make the returned values include the closing paren at the end (if exists)
```

File: source/served/ddoc.d [hunk 3]
```diff
@@ -34,71 +121,39 @@ MarkedString[] ddocToMarked(string ddoc)
...
-			wroteSomething = true;
 		}
-		wasHeader = tok.text.length && tok.text[$ - 1] == ':';
 	}
 	return output;
 }
 
-string[string] markdownMacros;
-
+private string[string] markdownMacros;
```
Comment (WebFreak001) [inline source/served/ddoc.d]: Let's keep this public in case some API/module wants to access or modify this.

File: source/served/ddoc.d [hunk 4]
```diff
@@ -3,14 +3,101 @@ module served.ddoc;
...
+		case "authors":
+		case "bugs":
+		case "date":
+		case "deprecated":
+		case "history":
+		default:
+			// Single line sections go on the same line as section titles. Multi
+			// line sections go on the line below.
+			import std.algorithm : find;
+			if (section.content.chomp().find('\n').empty)
```
Comment (WebFreak001) [inline source/served/ddoc.d]: I think canFind() would be cleaner here and you could extend this to `canFind(only("\r\n", "\n", "\r"))`

File: source/served/ddoc.d [hunk 5]
```diff
@@ -3,14 +3,101 @@ module served.ddoc;
...
-	return expand(lexer, markdownMacros, false).replace("&#36;", "$");
+	// Parse ddoc. Return if exception.
+	Comment comment;
+	try
+	{
+		comment = parseComment(prepareDDoc(ddoc), markdownMacros);
+	}
+	catch (Exception e)
+	{
+		return ddoc;
```
Comment (WebFreak001) [inline source/served/ddoc.d]: Could you fall back to returning the expanded & prepared ddoc macros like before if it fails to parse?

File: source/served/commands/calltips.d (hunk 1 above)
Comment (jonathanballs) [reply source/served/commands/calltips.d]: I'll make it work without a new line but I feel that any attempts to just do some "quick parsing" will probably lead to buggy results.

Comment (WebFreak001) [reply source/served/commands/calltips.d]: It would need to count parenthesis (but not in strings) to find out where it is right now and it could stop at a `{`

File: source/served/ddoc.d (hunk 4 above)
Comment (jonathanballs) [reply source/served/ddoc.d]: Right. I'm not super familiar with all the of `std.algorithm` yet.

File: source/served/ddoc.d (hunk 5 above)
Comment (jonathanballs) [reply source/served/ddoc.d]: I was a bit concerned about the Lexer throwing an exception in prepare Ddoc so I left it out. What do you think?

Comment (WebFreak001) [reply source/served/ddoc.d]: Have you tried if it can throw with any invalid input? All it's doing is tokenizing and not interpreting what it means so I don't think that it will throw anything

Comment (jonathanballs) [reply source/served/ddoc.d]: Yeah just tried. `prepareDDoc("\n\n汉语\n---");` will throw an exception.
